#!/bin/bash

# Shell script to copy file to a new, with date added to filename, 
# before the extension.
#
# Author: Manuel López Mateos, under GPL-3.0 License
#	  https://manuel.lopez-mateos.net
# 
# Last change: Jun 20, 2023, 21:16. Delete colon and add h after Hour, m after Minutes and s after Secons
#              (some servers don't allow upload files with colon in file name)
# Jun 20, 2023. Add colon after Hour and Minutes
# Sep 24, 2020
# ------------------------------------------------------------

now=$(date +"%b%d-%Y-%Hh%Mm%Ss")

FILE="$1"


name="${FILE%.*}"
ext="${FILE##*.}"

cp -v $FILE $name-$now.$ext

